#!/usr/bin/env python
# coding: utf-8

# In[21]:


import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
get_ipython().run_line_magic('matplotlib', 'inline')


# # Import Garmin Data

# In[2]:


garmin = pd.read_csv("garmin_data.csv") 


# In[3]:


garmin.head()


# # Basic Stats on Garmin data

# In[8]:


total_distance = garmin['Distance'].sum(skipna=True)
print("Total Distance ran", total_distance, "miles")


# In[14]:


mean_distance = garmin['Distance'].median()
print("Average Distance ran", mean_distance, "miles")


# In[13]:


garmin['Distance'].describe()


# # Import Strava Data

# In[15]:


strava = pd.read_csv("activities.csv") 


# In[27]:


strava.head(20)


# In[17]:


total_distance1 = strava['Distance'].sum(skipna=True)
print("Total Distance ran", total_distance1, "miles")


# In[18]:


mean_distance1 = strava['Distance'].median()
print("Average Distance ran", mean_distance1, "miles")


# In[20]:


strava['Distance'].describe()


# In[25]:


sns.countplot(garmin['Distance'])


# In[26]:


#heatmap
corr = garmin.corr()
sns.heatmap(corr, 
        xticklabels=corr.columns,
        yticklabels=corr.columns)


# In[29]:


# visualize the distribution of the finish times
Activity = strava[strava['Activity Name']==1]
Distance = strava[strava['Distance']==1]

fig = plt.figure(figsize=(15,5))
ax = fig.add_subplot(111)
ax.hist(Activity['Elapsed Time'], bins=20, color='blue', alpha=0.7, 
        histtype='bar', ec='ivory', label='Activity', linewidth=1)
ax.hist(Distance['Elapsed Time'], bins=20, color='yellow', alpha=0.8, 
        histtype='bar', ec='ivory', label='Distance', linewidth=1)

ax.set_xlim([8000, 25000])
ax.set_title('Distribution of Finish Times', size=30)
ax.set_xlabel('Finish Times in Seconds', size=15)
ax.set_ylabel('Frequency', size=15)
ax.legend();


# In[ ]:




